In [2]:
import pandas as pd

df = pd.read_csv("daily_prices_historical.csv")

print(df.head())
print(df.info())
print(df.isnull().sum())

         date   value
0  1973-08-20  0.6735
1  1973-08-21  0.6710
2  1973-08-22  0.6580
3  1973-08-23  0.6675
4  1973-08-24  0.6660
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12029 entries, 0 to 12028
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    12029 non-null  object
 1   value   12029 non-null  float64
dtypes: float64(1), object(1)
memory usage: 188.1+ KB
None
date     0
value    0
dtype: int64

In [4]:
import pandas as pd

# remove duplicates
df = df.drop_duplicates()

# standardize column names to lowercase
df.columns = df.columns.str.lower()

# convert date column to datetime
if 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'])

# fill missing values (forward fill)
df = df.ffill()

# remove impossible prices if the column exists
if 'close' in df.columns:
    df = df[df['close'] > 0]
else:
    print("Warning: 'close' column not found. Available columns:", df.columns)from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

df.columns = df.columns.str.lower().str.strip()

X = df[['open','high','low','close','volume']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(X_scaled)

Warning: 'close' column not found. Available columns: Index(['date', 'value'], dtype='object')

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# clean column names
df.columns = df.columns.str.lower().str.strip()

# select numeric columns automatically
X = df.select_dtypes(include='number')

# scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# run KMeans
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(X_scaled)

In [10]:
print(df.columns)
df.columns = df.columns.str.strip()
df.head()

Index(['date', 'value', 'cluster'], dtype='object')

        date   value  cluster
0 1973-08-20  0.6735        1
1 1973-08-21  0.6710        1
2 1973-08-22  0.6580        1
3 1973-08-23  0.6675        1
4 1973-08-24  0.6660        1

In [13]:
print(df.columns)

Index(['date', 'value', 'cluster'], dtype='object')

In [14]:
df.head()

        date   value  cluster
0 1973-08-20  0.6735        1
1 1973-08-21  0.6710        1
2 1973-08-22  0.6580        1
3 1973-08-23  0.6675        1
4 1973-08-24  0.6660        1

In [18]:
print(df.columns)

Index(['date', 'value', 'cluster'], dtype='object')

In [21]:
print("Columns:", df.columns.tolist())
print("Headline columns:", headline_cols if 'headline_cols' in locals() else "not created")
print(df[headline_cols].head() if 'headline_cols' in locals() and headline_cols else "No headline columns")

Columns: ['date', 'value', 'cluster', 'combined_news']
Headline columns: ['combined_news']
Empty DataFrame
Columns: [combined_news]
Index: []

In [22]:
print(df['combined_news'].head(10))
print(df['combined_news'].str.len().describe())

Series([], Name: combined_news, dtype: object)
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: combined_news, dtype: float64

In [23]:
print(df.columns.tolist())
print(df.head())

['date', 'value', 'cluster', 'combined_news']
Empty DataFrame
Columns: [date, value, cluster, combined_news]
Index: []

In [25]:
df.columns = df.columns.str.strip()
df_clean = df.drop(columns=['distance'], errors='ignore')
df_clean.to_csv("cleaned_daily_prices.csv", index=False)