In [1]:
import pandas as pd

df = pd.read_csv("wikipedia_visits.csv")

print(df.head())
print(df.info())
print(df.isnull().sum())

         date         y
0  2007-12-10  9.590761
1  2007-12-11  8.519590
2  2007-12-12  8.183677
3  2007-12-13  8.072467
4  2007-12-14  7.893572
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2905 entries, 0 to 2904
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    2905 non-null   object
 1   y       2905 non-null   float64
dtypes: float64(1), object(1)
memory usage: 45.5+ KB
None
date    0
y       0
dtype: int64

In [3]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [5]:
df.head()

         date         y
0  2007-12-10  9.590761
1  2007-12-11  8.519590
2  2007-12-12  8.183677
3  2007-12-13  8.072467
4  2007-12-14  7.893572

In [11]:
print("Columns:", df.columns.tolist())
print(df.head())

Columns: ['date', 'y']
         date         y
0  2007-12-10  9.590761
1  2007-12-11  8.519590
2  2007-12-12  8.183677
3  2007-12-13  8.072467
4  2007-12-14  7.893572

In [14]:
df.head()

         date         y
0  2007-12-10  9.590761
1  2007-12-11  8.519590
2  2007-12-12  8.183677
3  2007-12-13  8.072467
4  2007-12-14  7.893572

In [21]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin_min

# Load or use your dataframe
# df = pd.read_csv("wikipedia_visits.cs")

# Select numeric columns for clustering
X = df.select_dtypes(include=['int64','float64'])

# Create KMeans model
kmeans = KMeans(n_clusters=3, random_state=42)

# Fit the model
kmeans.fit(X)

# Find closest cluster center and distance for each point
closest, distances = pairwise_distances_argmin_min(X, kmeans.cluster_centers_)

# Store cluster labels
df["cluster"] = closest

# Store distance to cluster center
df["distance"] = distances

# Define outlier threshold (95th percentile)
threshold = df["distance"].quantile(0.95)

# Remove outliers
clean_df = df[df["distance"] < threshold]

# Reset index
clean_df = clean_df.reset_index(drop=True)

print(clean_df.head())

         date         y  cluster  distance
0  2007-12-10  9.590761        0  0.248122
1  2007-12-11  8.519590        1  0.064138
2  2007-12-12  8.183677        1  0.271776
3  2007-12-13  8.072467        1  0.382985
4  2007-12-14  7.893572        2  0.413568

In [23]:
clean_df.columns

Index(['date', 'y', 'cluster', 'distance'], dtype='object')

In [24]:
clean_df.to_csv("wikipedia_visits_cleaned.csv", index=False)